### ISSUE TITLE
Python Examples - Operations Audit

### ISSUE THREAD

**Issue by tebanieo** [aws-samples/aws-dynamodb-examples#124]
The newly created [Operations](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/Operations.md) page needs auditing to ensure all the operations listed in the page have a matching example.

**Comment by ChinoUkaegbu** [comment]
- <b>[WorkingWithItems:](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithItems)</b> all documented but `DeleteItemConditional` seems to be referencing [this file](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithItems/delete_item2.py) which is named `delete_item2.py` instead of `delete_item_conditional.py` as is the format with the other conditional operations
- <b>[WorkingWithQueries:](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithQueries)</b> all documented apart from [pagination.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/pagination.py), [query-scan-count.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query-scan-count.py), [query_begins_with.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query_begins_with.py) and [query_equals.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query_equals.py)
- <b>[WorkingWithIndexes:](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithIndexes)</b> is referenced in the README but doesn't exist yet
- <b>[WorkingWithScans:](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithScans)</b> all documented
- <b>[WorkingWithTables:](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithTables)</b> all documented apart from [add_gsi.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/add_gsi.py) and [enable_continuous_backups.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/enable_continuous_backups.py). Additionally I suggest renaming [table_change_to_on-demand.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/table_change_to_on-demand.py) and [table_change_to_provisioned.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/table_change_to_provisioned.py) to `update_table_one-demand` and `update_table_provisioned` so it's consistent with what's in Operations.MD
- <b>[WorkingWithPartiQL:](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithPartiQL)</b> all documented apart from [paginated-query-batch-execute-statement.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithPartiQL/paginated-query-batch-execute-statement.py) and [paginated-select-statement.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithPartiQL/paginated-select-statement.py)
- <b>[WorkingWithCustomBackoffRetry:](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithCustomBackoffRetry)</b> exists but is not documented in README

**Comment by ChinoUkaegbu** [comment]
Also, there's a mention of 'Count' in [Operations.md](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/Operations.md) but I'm not sure what example file that's referring to...possibly [query-scan-count.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query-scan-count.py). Aside from that, the other operations in the table with ✅ are present and those with ❌ are absent.

**Comment by tebanieo** [comment]
Thanks @ChinoUkaegbu for the audit. 

This is a summary of the work that needs to be completed on this issue:

- [ ] Fix [DeleteItemConditional](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithItems/delete_item2.py) reference to point to `delete_item_conditional.py`.
- [ ] Add, [pagination.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/pagination.py), [query-scan-count.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query-scan-count.py), [query_begins_with.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query_begins_with.py) and [query_equals.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query_equals.py) to the [Operations.md](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/Operations.md) file. 
- [ ] Identify the examples that matches the `WorkingWithIndexes` description, the examples might also be present under a different category. 
- [ ] Add entry for [add_gsi.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/add_gsi.py) and [enable_continuous_backups.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/enable_continuous_backups.py). 
- [ ] Renaming [table_change_to_on-demand.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/table_change_to_on-demand.py) and [table_change_to_provisioned.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/control_plane/WorkingWithTables/table_change_to_provisioned.py) to `update_table_on-demand` and `update_table_provisioned` so it's consistent with what's in Operations.MD
- [ ] Add entry for [paginated-query-batch-execute-statement.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithPartiQL/paginated-query-batch-execute-statement.py) and [paginated-select-statement.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithPartiQL/paginated-select-statement.py)
- [ ] Add entry for [WorkingWithCustomBackoffRetry](https://github.com/aws-samples/aws-dynamodb-examples/tree/master/examples/SDK/python/data_plane/WorkingWithCustomBackoffRetry)</b> exists but is not documented in README
- [ ] Update `Count` in the table to match [query-scan-count.py](https://github.com/aws-samples/aws-dynamodb-examples/blob/master/examples/SDK/python/data_plane/WorkingWithQueries/query-scan-count.py).

**Comment by tebanieo** [comment]
Thanks to @ChinoUkaegbu to complete the python audit, new issue has ben created to track modifications #142
